kind: pipeline
type: docker
name: fosspop

steps:
    - name: test
      image: emscripten/emsdk
      commands:
          - echo "Current working directory"
          - pwd
          - echo "Current directory contents"
          - ls -la
          - apt update
          - apt install -y libsdl2-dev
          - apt install -y libsdl2-image-dev
          - apt install -y libsdl2-mixer-dev
          - mkdir $(pwd)/cmake_tests
          - cd cmake_tests
          - cmake $(pwd)/..
          - make
          - ./tests/FossPop_Tests
