FROM emscripten/emsdk

# Installs SDL2 and SDL_Image
RUN apt update && apt install -y libsdl2-dev && apt install -y libsdl2-image-dev

# Copies source files
COPY src /src/src
COPY tests /src/tests
COPY include /src/include
COPY public /src/public
COPY assets /src/assets
COPY CMakeLists.txt /src/CMakeLists.txt

# Compiles test suite
RUN mkdir cmake_tests
WORKDIR cmake_tests
RUN cmake .. && make

# Runs test suite
CMD ["./tests/FossPop_Tests"]